### ISSUE TITLE
phpIPAM_GetIPRanges

### ISSUE THREAD

**Issue by eduardoscheidet** [jbowdre/phpIPAM-for-vRA8#1]
Hello @jbowdre 
I am trying to integrating your plugin into my vra 8.5 and show me an error: Execution of action phpIPAM_GetIPRanges failed on provider side: 'data'

Logs:
[2021-10-04 18:33:40,623] [INFO] - Querying for auth credentials
[2021-10-04 18:33:40,659] [INFO] - Credentials obtained successfully!
Traceback (most recent call last):
  File "abx_wrapper.py", line 325, in main
    response = exec_function(wrapperCtx, request, f)
  File "abx_wrapper.py", line 223, in exec_function
    funcResult = handle(ctx, req)
  File "/function/source.py", line 42, in handler
    return ipam.get_ip_ranges()
  File "/function/vra_ipam_utils/ipam.py", line 64, in get_ip_ranges
    result = self.do_get_ip_ranges(auth_credentials, cert)
  File "/function/source.py", line 68, in do_get_ip_ranges
    subnets = subnets.json()['data']
KeyError: 'data'

i dont know if this error is because some configuration on phpIPAM or the version of my vRA.

If you can help, i really appreciate that.

Regards,

**Comment by jbowdre** [comment]
Hi @eduardoscheidet,

I think you may have stumbled upon a glaring ommission in my admittedly-poor documentation. Looking at the code above the line where it pukes:

```python
    # Request list of subnets
    subnet_uri = f'{uri}/subnets/'
    ipRanges = []
    subnets = requests.get(f'{subnet_uri}?filter_by=isPool&filter_value=1', headers=token, verify=cert)
    subnets = subnets.json()['data']
```

It's only going to grab subnets which are marked with `isPool` - those which have been set as Pools within the phpIPAM configuration for that subnet.
![image](https://user-images.githubusercontent.com/61015723/135907872-a546e554-bff7-44ea-bce2-127bace89d15.png)

I touched on that briefly on my blog post but apparently failed to mention it in the local README. I'll update that. :)

In your case, I'd suggest either tweaking phpIPAM to mark your subnets as pools or else change line 67 to remove that filter:
```python
    subnets = requests.get(f'{subnet_uri}', headers=token, verify=cert)
```

Let me know if either of those work or if you continue to get the error.

Cheers,
John

**Comment by jbowdre** [comment]
Awesome, I'm glad to hear it!
