### ISSUE TITLE
Set MAC address , VLAN, Hostname using ABX or vRO in 8.6.2 version

### ISSUE THREAD

**Issue by ratheeshpc** [jbowdre/phpIPAM-for-vRA8#4]
Hello,

I have Django based program to talk to IPAM to get IP,Hostname, MAC, VLAN etc. This Django also talk to AD, internal costing tool as well. I am looking for an option to update MAC, Hostname, IP , Mac address type in new version of vRA7vRO. Found your website so promising and thought of asking here.

As of now I am using vRO(7.5) workflow to update properties of VM using payload. Code shared below.

Says: vRA>Subscriptions>vRO>API Calls to Django> Get below values

virtualMachineAddOrUpdateProperties = new Properties ();
virtualMachineAddOrUpdateProperties.put('Name', hostname);
virtualMachineAddOrUpdateProperties.put('VirtualMachine.Network0.MacAddressType', 'static');
virtualMachineAddOrUpdateProperties.put('VirtualMachine.Network0.MacAddress', mac);
virtualMachineAddOrUpdateProperties.put('VirtualMachine.Network0.Name', "VLAN"+vlan);

And I have couple of API calls to Django program to get above values. How do I implement same in vRA7vRO 8.6.2

Is there any way to use your repo to build my Django application as IPAM ? Please guide

**Comment by jbowdre** [comment]
Unfortunately I don't think the code in this repo will really be terribly helpful for implementing this as an ABX/vRO action. The Python code for interacting with the phpIPAM API should be similar, but the communication with the vRA/vRO side of things will be completely different.

**Comment by ratheeshpc** [comment]
Okay. Do you have any idea on above mentioned issue or any hint to me ?

**Comment by jbowdre** [comment]
Unfortunately I don't, at least not off the top of my head (or from a quick bit of searching). 

You might ask on VMware's forum to see if someone there has any ideas. That's been a big help for my efforts:
https://communities.vmware.com/t5/VMware-vRealize/ct-p/13000-home
